# Generated by Django 4.0.5 on 2022-06-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='curso',
            new_name='cursos',
        ),
    ]
